import { EngineConfigurationOption, Text } from '@sonolus/core'

export const optionsDefinition = {
    speed: {
        name: Text.Speed,
        category: 'gameplay',
        standard: true,
        advanced: true,
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    hidden: {
        name: Text.Hidden,
        category: 'gameplay',
        standard: true,
        advanced: true,
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    noteSpeed: {
        name: Text.NoteSpeed,
        category: 'gameplay',
        scope: 'Mania',
        type: 'slider',
        def: 10,
        min: 1,
        max: 80,
        step: 0.1,
    },
    fullscreenInputEnabled: {
        name: 'Fullscreen Input',
        category: 'gameplay',
        scope: 'Mania',
        type: 'toggle',
        def: 0,
    },
    mirror: {
        name: Text.Mirror,
        category: 'gameplay',
        type: 'toggle',
        def: 0,
    },
    sfxEnabled: {
        name: Text.Effect,
        category: 'audio',
        scope: 'Mania',
        type: 'toggle',
        def: 1,
    },
    autoSFX: {
        name: Text.EffectAuto,
        category: 'audio',
        scope: 'Mania',
        type: 'toggle',
        def: 0,
    },
    noteSize: {
        name: Text.NoteSize,
        category: 'graphics',
        scope: 'Mania',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    noteEffectEnabled: {
        name: Text.NoteEffect,
        category: 'graphics',
        scope: 'Mania',
        type: 'toggle',
        def: 1,
    },
    noteEffectSize: {
        name: Text.NoteEffectSize,
        category: 'graphics',
        scope: 'Mania',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    connectorAlpha: {
        name: Text.ConnectorAlpha,
        category: 'graphics',
        scope: 'Mania',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    laneEffectEnabled: {
        name: Text.LaneEffect,
        category: 'graphics',
        scope: 'Mania',
        type: 'toggle',
        def: 1,
    },
    judgeLinePosition: {
        name: Text.JudgelinePosition,
        category: 'graphics',
        scope: 'Mania',
        type: 'slider',
        def: 0.85,
        min: 0.5,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    stageCover: {
        name: Text.StageCoverVertical,
        category: 'graphics',
        scope: 'Mania',
        advanced: true,
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    stageDirection: {
        name: Text.StageDirection,
        category: 'graphics',
        scope: 'Mania',
        type: 'select',
        def: 1,
        values: [Text.Down, Text.Right, Text.Up, Text.Left],
    },
    stageSize: {
        name: Text.StageSize,
        category: 'graphics',
        scope: 'Mania',
        type: 'slider',
        def: 0.8,
        min: 0.1,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    lockStageAspectRatio: {
        name: Text.StageAspectratioLock,
        category: 'graphics',
        scope: 'Mania',
        type: 'toggle',
        def: 0,
    },
    previewVerticalScale: {
        name: Text.PreviewScaleVertical,
        category: 'miscellaneous',
        scope: 'Mania',
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    previewMeasure: {
        name: Text.PreviewMeasure,
        category: 'miscellaneous',
        scope: 'Mania',
        type: 'toggle',
        def: 1,
    },
    previewBeat: {
        name: Text.PreviewBeat,
        category: 'miscellaneous',
        scope: 'Mania',
        type: 'toggle',
        def: 1,
    },
    previewTime: {
        name: Text.PreviewTime,
        category: 'miscellaneous',
        scope: 'Mania',
        type: 'toggle',
        def: 1,
    },
    previewBpm: {
        name: Text.PreviewBpm,
        category: 'miscellaneous',
        scope: 'Mania',
        type: 'toggle',
        def: 1,
    },
} satisfies Record<string, EngineConfigurationOption>
